### PR TITLE
version bump to 0.38.0

### PR DESCRIPTION
**Pull request by dgkuester-nist**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dgkuester-nist** [comment]
@conda-forge-admin, please rerender

**Comment by dgkuester-nist** [comment]
@conda-forge/core

I'm hoping for some advice troubleshooting two problems:

1. The same recipe that passed when labbench was first approved for conda-forge fails with cryptic error messages (see #1 , even before the version bump). 
2. No packages are being built for aarch64 for this pure-python module, even though manual installs of all of the dependencies proceeds without any problems on my Mac.

Thanks in advance for any tips or hints you can provide on this!

**Comment by ocefpaf** [comment]
You need to update the checksum here. The error message is telling you that. You can click in the sdist on PyPI and then on view hashes:

Screenshot from 2024-07-10 18-28-02

**Comment by dgkuester-nist** [comment]
> You need to update the checksum here. The error message is telling you that. You can click in the sdist on PyPI and then on view hashes:
> 
> Screenshot from 2024-07-10 18-28-02

Thanks for the quick reply, and accommodating the easy answer on hashes my first maintenance update! 

Do you have any insights about how I can work toward getting packages for ARM platforms?

**Comment by isuruf** [comment]
You can make this pacakge `noarch: python` since it's a pure-python package and the packages will be installable on all platforms.

**Comment by isuruf** [comment]
The way I had it is the recommended way. You can ignore the linter

**Comment by dgkuester-nist** [comment]
@isuruf thanks for being so responsive! The reason that it wasn't `noarch` before was to support a windows-only dependency on the `comtypes` library, which doesn't exist on all platforms. What I've just committed removed comments that tag that as windows-specific.

If necessary, I can leave it this way, with `comtypes` as an optional dependency. Is there a way to specify windows-specific dependencies that is compatible with `noarch`?

**Comment by isuruf** [comment]
>  Is there a way to specify windows-specific dependencies that is compatible with noarch?

Yes, see https://github.com/conda-forge/labbench-feedstock/pull/2/commits/3771cf46f3f14d40b11716fd2d908382e0cb0251

**Comment by dgkuester-nist** [comment]
Ahhh I see and then I blew away that change. I apologize for missing it, am reverting back to your version.

**Comment by dgkuester-nist** [comment]
Are any further edits needed to support OS X? I'm guessing based on your expertise that the answer for the updated recipe no, so I'll merge this one. Can pull another update later if necessary. Thanks for your support here!

**Comment by h-vetinari** [comment]
You should also reapply https://github.com/conda-forge/labbench-feedstock/pull/2/commits/9009bda50559f50ea140ce4cca47d8ca7e2b1275

**Comment by dgkuester-nist** [comment]
@h-vetinari - implemented that change in #3 with a version bump. Thanks for being so friendly in accommodating my newness here!

**Pull request merged**
